apiVersion: v1
kind: Service
metadata:
  name: officecli-platform-postgres-headless
  namespace: officecli
spec:
  clusterIP: None
  selector:
    app: officecli-platform-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
