package imagewatermark

import (
	"errors"
	"fmt"
	"image"
	"image/color"
	"image/draw"
	"image/jpeg"
	"image/png"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"golang.org/x/image/font"
	"golang.org/x/image/font/basicfont"
	"golang.org/x/image/font/opentype"
	"golang.org/x/image/math/fixed"

	qrcode "github.com/skip2/go-qrcode"
)

type Options struct{}

const defaultFootmarkText = "Generated by OfficeDex."
const cornerFootmarkText = "Generated by OfficeDex AI."
const footerPoweredByText = "Powered by OfficeCLI"
const footerRightTitleText = "Try OfficeDex FREE"
const footerRightMetaText = "officedex.ai  AI image generator"
const footmarkQRCodeContent = "https://officedex.ai/"

var (
	footmarkDarkShadow = color.NRGBA{R: 0, G: 0, B: 0, A: 112}
	footmarkDarkText   = color.NRGBA{R: 38, G: 42, B: 48, A: 218}
	footmarkLightText  = color.NRGBA{R: 255, G: 255, B: 255, A: 238}
	qrBackground       = color.RGBA{R: 255, G: 255, B: 255, A: 255}
	qrForeground       = color.RGBA{R: 18, G: 22, B: 28, A: 255}
)

// Apply overwrites path with a watermarked version. The original file is only
// replaced after the new image has been fully encoded to a sibling temp file.
func Apply(path string, opts Options) error {
	if strings.TrimSpace(path) == "" {
		return errors.New("image watermark: empty path")
	}
	src, format, mode, err := decode(path)
	if err != nil {
		return err
	}
	output, err := render(src, opts)
	if err != nil {
		return err
	}
	return encodeReplace(path, format, mode, output)
}

func decode(path string) (image.Image, string, os.FileMode, error) {
	info, err := os.Stat(path)
	if err != nil {
		return nil, "", 0, fmt.Errorf("image watermark: stat: %w", err)
	}
	if info.IsDir() {
		return nil, "", 0, errors.New("image watermark: path is a directory")
	}
	f, err := os.Open(path)
	if err != nil {
		return nil, "", 0, fmt.Errorf("image watermark: open: %w", err)
	}
	defer f.Close()

	ext := strings.ToLower(strings.TrimPrefix(filepath.Ext(path), "."))
	switch ext {
	case "png":
		img, err := png.Decode(f)
		if err != nil {
			return nil, "", 0, fmt.Errorf("image watermark: decode png: %w", err)
		}
		return img, "png", info.Mode(), nil
	case "jpg", "jpeg":
		img, err := jpeg.Decode(f)
		if err != nil {
			return nil, "", 0, fmt.Errorf("image watermark: decode jpeg: %w", err)
		}
		return img, "jpeg", info.Mode(), nil
	default:
		return nil, "", 0, fmt.Errorf("image watermark: unsupported extension %q", ext)
	}
}

func render(src image.Image, opts Options) (*image.RGBA, error) {
	bounds := src.Bounds()
	width, height := bounds.Dx(), bounds.Dy()
	if width <= 0 || height <= 0 {
		return nil, errors.New("image watermark: invalid image bounds")
	}

	footerMainFace := loadFace(float64(clamp(width/96, 8, 12)))
	defer footerMainFace.Close()
	footerSubFace := loadFace(float64(clamp(width/192, 4, 6)))
	defer footerSubFace.Close()
	footerRightTitleFace := loadFace(float64(clamp(width/128, 6, 10)))
	defer footerRightTitleFace.Close()
	footerRightMetaFace := loadFace(float64(clamp(width/192, 4, 7)))
	defer footerRightMetaFace.Close()
	cornerFace := loadFace(float64(clamp(width/42, 12, 20)))
	defer cornerFace.Close()

	footerHeight := bottomWatermarkHeight(width, height)
	out := image.NewRGBA(image.Rect(0, 0, width, height+footerHeight))
	draw.Draw(out, image.Rect(0, 0, width, height), src, bounds.Min, draw.Src)
	if err := drawCornerFootmark(out, cornerFace, width, height, cornerFootmarkText); err != nil {
		return nil, err
	}
	if err := drawBottomFootmark(out, footerMainFace, footerSubFace, footerRightTitleFace, footerRightMetaFace, width, height, footerHeight); err != nil {
		return nil, err
	}
	return out, nil
}

func bottomWatermarkHeight(width, height int) int {
	base := clamp(width/10, 54, 96)
	if height > 0 {
		maxHeight := height / 3
		if base > maxHeight && maxHeight >= 44 {
			base = maxHeight
		}
	}
	return base
}

func drawBottomFootmark(img *image.RGBA, mainFace, subFace, rightTitleFace, rightMetaFace font.Face, width, originalHeight, footerHeight int) error {
	footerRect := image.Rect(0, originalHeight, width, originalHeight+footerHeight)
	draw.Draw(img, footerRect, image.NewUniform(color.RGBA{R: 255, G: 255, B: 255, A: 255}), image.Point{}, draw.Src)
	draw.Draw(img, image.Rect(0, originalHeight, width, originalHeight+1), image.NewUniform(color.RGBA{R: 220, G: 224, B: 232, A: 255}), image.Point{}, draw.Src)

	outerPad := clamp(width/36, 12, 28)
	qrSize := clamp(footerHeight-outerPad, 36, 72)
	if qrSize > width/6 {
		qrSize = width / 6
	}
	if qrSize < 32 {
		qrSize = 32
	}

	textColor := color.NRGBA{R: 24, G: 29, B: 38, A: 255}
	mutedTextColor := color.NRGBA{R: 76, G: 84, B: 98, A: 255}

	leftText := defaultFootmarkText
	leftX := outerPad
	mainHeight := lineHeight(mainFace)
	subHeight := lineHeight(subFace)
	rowGap := clamp(footerHeight/16, 3, 6)
	leftGroupHeight := mainHeight + rowGap + subHeight
	leftTop := originalHeight + (footerHeight-leftGroupHeight)/2
	if leftTop < originalHeight+4 {
		leftTop = originalHeight + 4
	}
	mainBaseline := leftTop + mainFace.Metrics().Ascent.Ceil()
	subBaseline := leftTop + mainHeight + rowGap + subFace.Metrics().Ascent.Ceil()
	drawBoldText(img, mainFace, leftText, leftX, mainBaseline, textColor)
	drawText(img, subFace, footerPoweredByText, leftX, subBaseline, mutedTextColor)

	dividerColor := color.NRGBA{R: 194, G: 200, B: 210, A: 255}
	rightTitle := footerRightTitleText
	rightMeta := footerRightMetaText
	rightTitleWidth := font.MeasureString(rightTitleFace, rightTitle).Ceil()
	rightMetaWidth := font.MeasureString(rightMetaFace, rightMeta).Ceil()
	rightTextWidth := maxInt(rightTitleWidth, rightMetaWidth)
	rightGap := clamp(width/70, 10, 18)
	dividerGap := clamp(width/100, 8, 14)
	dividerWidth := 1
	rightGroupWidth := qrSize + dividerGap + dividerWidth + dividerGap + rightTextWidth
	rightGroupX := width - outerPad - rightGroupWidth
	leftTextWidth := maxInt(font.MeasureString(mainFace, leftText).Ceil(), font.MeasureString(subFace, footerPoweredByText).Ceil())
	minRightGroupX := leftX + leftTextWidth + rightGap
	if rightGroupX < minRightGroupX {
		availableTextWidth := width - outerPad - minRightGroupX - qrSize - dividerGap*2 - dividerWidth
		rightTitle = elideToWidth(rightTitleFace, rightTitle, availableTextWidth)
		rightMeta = elideToWidth(rightMetaFace, rightMeta, availableTextWidth)
		rightTextWidth = maxInt(font.MeasureString(rightTitleFace, rightTitle).Ceil(), font.MeasureString(rightMetaFace, rightMeta).Ceil())
		rightGroupWidth = qrSize + dividerGap + dividerWidth + dividerGap + rightTextWidth
		rightGroupX = width - outerPad - rightGroupWidth
		if rightGroupX < minRightGroupX {
			rightGroupX = minRightGroupX
		}
	}

	qrX := rightGroupX
	qrY := originalHeight + (footerHeight-qrSize)/2
	if qrY < originalHeight {
		qrY = originalHeight
	}

	dividerX := qrX + qrSize + dividerGap
	dividerHeight := clamp(qrSize*3/5, 24, 44)
	dividerY := originalHeight + (footerHeight-dividerHeight)/2
	draw.Draw(img, image.Rect(dividerX, dividerY, dividerX+dividerWidth, dividerY+dividerHeight), image.NewUniform(dividerColor), image.Point{}, draw.Src)

	rightTextX := dividerX + dividerWidth + dividerGap
	rightTitleHeight := lineHeight(rightTitleFace)
	rightMetaHeight := lineHeight(rightMetaFace)
	rightTextGap := clamp(footerHeight/18, 3, 5)
	rightTextBlockHeight := rightTitleHeight + rightTextGap + rightMetaHeight
	rightTextTop := originalHeight + (footerHeight-rightTextBlockHeight)/2
	if rightTitle != "" {
		titleBaseline := rightTextTop + rightTitleFace.Metrics().Ascent.Ceil()
		drawBoldText(img, rightTitleFace, rightTitle, rightTextX, titleBaseline, textColor)
	}
	if rightMeta != "" {
		metaBaseline := rightTextTop + rightTitleHeight + rightTextGap + rightMetaFace.Metrics().Ascent.Ceil()
		drawText(img, rightMetaFace, rightMeta, rightTextX, metaBaseline, mutedTextColor)
	}

	return drawQRCode(img, image.Rect(qrX, qrY, qrX+qrSize, qrY+qrSize), footmarkQRCodeContent)
}

func elideToWidth(face font.Face, text string, maxWidth int) string {
	if maxWidth <= 0 {
		return ""
	}
	if font.MeasureString(face, text).Ceil() <= maxWidth {
		return text
	}
	const suffix = "..."
	suffixWidth := font.MeasureString(face, suffix).Ceil()
	if suffixWidth > maxWidth {
		return ""
	}
	runes := []rune(text)
	for len(runes) > 0 {
		candidate := string(runes) + suffix
		if font.MeasureString(face, candidate).Ceil() <= maxWidth {
			return candidate
		}
		runes = runes[:len(runes)-1]
	}
	return ""
}

func drawCornerFootmark(img *image.RGBA, face font.Face, width, height int, text string) error {
	outerPad := clamp(width/42, 12, 28)
	textWidth := font.MeasureString(face, text).Ceil()
	textHeight := lineHeight(face)
	x := width - outerPad - textWidth
	if x < outerPad {
		x = outerPad
	}
	y := height - outerPad - textHeight
	if y < outerPad {
		y = outerPad
	}
	baseline := y + face.Metrics().Ascent.Ceil()
	foreground, shadow := cornerFootmarkPalette(img, image.Rect(x, y, x+textWidth, y+textHeight).Inset(-4))
	if shadow.A > 0 {
		drawText(img, face, text, x+1, baseline+1, shadow)
	}
	drawText(img, face, text, x, baseline, foreground)
	return nil
}

func drawQRCode(img *image.RGBA, rect image.Rectangle, content string) error {
	code, err := qrcode.New(content, qrcode.Medium)
	if err != nil {
		return fmt.Errorf("image watermark: create qr code: %w", err)
	}
	bitmap := code.Bitmap()
	if len(bitmap) == 0 || len(bitmap[0]) == 0 || rect.Empty() {
		return nil
	}
	for y := rect.Min.Y; y < rect.Max.Y; y++ {
		srcY := (y - rect.Min.Y) * len(bitmap) / rect.Dy()
		for x := rect.Min.X; x < rect.Max.X; x++ {
			srcX := (x - rect.Min.X) * len(bitmap[srcY]) / rect.Dx()
			pixel := qrBackground
			if bitmap[srcY][srcX] {
				pixel = qrForeground
			}
			img.SetRGBA(x, y, pixel)
		}
	}
	return nil
}

func cornerFootmarkPalette(img image.Image, rect image.Rectangle) (foreground, shadow color.NRGBA) {
	if averageLuma(img, rect) > 172 {
		return footmarkDarkText, color.NRGBA{}
	}
	return footmarkLightText, footmarkDarkShadow
}

func averageLuma(img image.Image, rect image.Rectangle) float64 {
	rect = rect.Intersect(img.Bounds())
	if rect.Empty() {
		return 0
	}
	var total float64
	var count int
	for y := rect.Min.Y; y < rect.Max.Y; y++ {
		for x := rect.Min.X; x < rect.Max.X; x++ {
			c := color.RGBAModel.Convert(img.At(x, y)).(color.RGBA)
			total += 0.299*float64(c.R) + 0.587*float64(c.G) + 0.114*float64(c.B)
			count++
		}
	}
	return total / float64(count)
}

func encodeReplace(path, format string, mode os.FileMode, img image.Image) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".watermark-*"+filepath.Ext(path))
	if err != nil {
		return fmt.Errorf("image watermark: create temp: %w", err)
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)

	switch format {
	case "png":
		err = png.Encode(tmp, img)
	case "jpeg":
		err = jpeg.Encode(tmp, img, &jpeg.Options{Quality: 95})
	default:
		err = fmt.Errorf("image watermark: unsupported format %q", format)
	}
	if closeErr := tmp.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		return fmt.Errorf("image watermark: encode: %w", err)
	}
	if mode != 0 {
		_ = os.Chmod(tmpPath, mode)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("image watermark: replace original: %w", err)
	}
	return nil
}

func drawText(img *image.RGBA, face font.Face, text string, x, y int, c color.Color) {
	d := font.Drawer{
		Dst:  img,
		Src:  image.NewUniform(c),
		Face: face,
		Dot:  fixed.P(x, y),
	}
	d.DrawString(text)
}

func drawBoldText(img *image.RGBA, face font.Face, text string, x, y int, c color.Color) {
	drawText(img, face, text, x, y, c)
	drawText(img, face, text, x+1, y, c)
}

func lineHeight(face font.Face) int {
	metrics := face.Metrics()
	return (metrics.Ascent + metrics.Descent).Ceil()
}

func maxInt(a, b int) int {
	if a > b {
		return a
	}
	return b
}

func loadFace(size float64) font.Face {
	for _, path := range fontCandidates() {
		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		if parsed, err := opentype.Parse(data); err == nil {
			if face, err := opentype.NewFace(parsed, &opentype.FaceOptions{Size: size, DPI: 144, Hinting: font.HintingFull}); err == nil {
				return face
			}
		}
		if collection, err := opentype.ParseCollection(data); err == nil {
			for i := 0; i < collection.NumFonts(); i++ {
				parsed, err := collection.Font(i)
				if err != nil {
					continue
				}
				if face, err := opentype.NewFace(parsed, &opentype.FaceOptions{Size: size, DPI: 144, Hinting: font.HintingFull}); err == nil {
					return face
				}
			}
		}
	}
	return basicfont.Face7x13
}

func fontCandidates() []string {
	switch runtime.GOOS {
	case "darwin":
		return []string{
			"/System/Library/Fonts/PingFang.ttc",
			"/System/Library/Fonts/STHeiti Light.ttc",
			"/System/Library/Fonts/Supplemental/Arial Unicode.ttf",
			"/System/Library/Fonts/Supplemental/Arial.ttf",
			"/Library/Fonts/Arial Unicode.ttf",
		}
	case "windows":
		win := os.Getenv("WINDIR")
		if win == "" {
			win = `C:\Windows`
		}
		return []string{
			filepath.Join(win, "Fonts", "msyh.ttc"),
			filepath.Join(win, "Fonts", "simhei.ttf"),
			filepath.Join(win, "Fonts", "arial.ttf"),
		}
	default:
		return []string{
			"/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
			"/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc",
			"/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
			"/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
		}
	}
}

func clamp(v, min, max int) int {
	if v < min {
		return min
	}
	if v > max {
		return max
	}
	return v
}
