ALTER TABLE users ADD COLUMN IF NOT EXISTS paid_entitlement BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS paid_entitlement_updated_at TIMESTAMPTZ NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS paid_entitlement_source VARCHAR(32) NOT NULL DEFAULT 'none';
